### PR TITLE
This isn’t StormGUI…

### PR DESCRIPTION
**Pull request by zax71**

### CODE REVIEW

**Comment by HEROOSTECH** [comment]
u forgor, this is citystom not stomgui lol

**Comment by HEROOSTECH** [comment]
https://github.com/CityWideMC/StomGUI

**Comment by HEROOSTECH** [comment]
i am stupid

**Comment by HEROOSTECH** [comment]
ur patch is for this project lol

**Comment by zax71** [comment]
:D

**Comment by HEROOSTECH** [comment]
Lol thanks i forgor to fix my readme

**Pull request merged**
